### ISSUE TITLE
It is not working with 5.0.0 version

### ISSUE THREAD

**Issue by Leoudayan** [Otto-AA/solid-filemanager#24]
Hi,

I tried to login with the pod that was created with the 5.0.0 stable version. When i tried to login with that pod, it gave me authentication error. Wont it work with the latest version?

**Comment by Otto-AA** [comment]
Hmm, I would have expected it to work.

As I basically only use the [solid-auth-client](https://github.com/solid/solid-auth-client) library for logging in and out and I didn't find a version constraint there, I thought it should work. If you are sure, that the login should have worked, could you try if this library works for you (or open an issue there)?

I wouldn't know what the error in this app could be, as it basically only calls `solidAuth.popupLogin({ popupUri })` (see [here](https://github.com/Otto-AA/solid-filemanager/blob/master/src/Actions/Actions.js#L6) for the source code)

**Comment by Leoudayan** [comment]
Hi, Thanks for your reply. Yes, the first level login works fine. But when i enter the URL and click enter into pod, it throws the following error,

Error: Error trying to parse <https://student1.solid.open.ac.uk/> as text/turtle: Error: Error: NamedNode IRI "https://student1.solid.open.ac.uk/!doctype html" must not contain unencoded spaces.: Error: Error: NamedNode IRI "https://student1.solid.open.ac.uk/!doctype html" must not contain unencoded spaces. at new t (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:26641) at t.value (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:543208) at x.uri_ref2 (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:272186) at x.node (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:269529) at x.nodeOrLiteral (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:274519) at x.path (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:265956) at x.item (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:265820) at x.subject (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:264402) at x.object (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:274222) at x.statement (https://otto-aa.github.io/solid-filemanager/build/static/js/2.42dfee7f.chunk.js:1:264214)

**Comment by Otto-AA** [comment]
Ok, I'm not really sure yet how to debug that. So here are some things I'd check (may seem obvious)
(1) The account you logged into has access to the storage location
(2) Does it work if you enter the public storage location of your pod (or e.g. https://otman.solid.community/public/ which probably isn't 5.0.0 though)?
(3) Do you have an idea from where the `"https://student1.solid.open.ac.uk/!doctype html"` comes? This seems pretty strange to me.

**Comment by Leoudayan** [comment]
Thanks for your reply. I dd some changes and now i am getting the following error. 
Error: <!doctype html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>No permission</title> <link rel="stylesheet" href="/common/css/bootstrap.min.css"> <link rel="stylesheet" href="/common/css/solid.css"> </head> <body> <div class="container"> <div class="page-header"> <h1>No permission to access this resource</h1> </div> <div class="alert alert-danger"> <p> You are currently logged in as <code>https://mano.solid.open.ac.uk/profile/card#me</code>, but do not have permission to access <code>https://mano.solid.open.ac.uk/public</code>. </p> <p> <button id="logout" type="button" class="btn btn-danger">Log out</button> </p> </div> </div> </div> <script src="/common/js/solid-auth-client.bundle.js"></script> <script src="/common/js/auth-buttons.js"></script> </body> </html>

Answering to your questions,
1. Yes, i checked it and i logged in through that account. In-fact your app works with 4.x.x versions. But 5.0.0 version is the one giving me these problems. 

2. Nope, it gives me same error as mentioned above.

3. I think this error is solved now. Its just the authentication problem now.

**Comment by Leoudayan** [comment]
I made the solid server open for public now. Please feel free to create a POD and test it if you have time. 

https://www.solid.open.ac.uk

After the 4.3.1 version, if you create an account, it wont give you the URL for your POD (not sure what causes it). So, once you create an account, click register again and click the Already have an account tab and login.

**Comment by Otto-AA** [comment]
Ok, I've found two issues:
First, it seems that the app now needs an additional authorization at your profile (https://mano.solid.open.ac.uk/profile/card#me -> A -> Grant access to https://otto-aa.github.io with at least Read and Write).

And secondly, the homepage now returns a html file whereas the old returned a turtle file (as it is the case for all other directories). So the home folder is currently unavailable, but as mentioned before you can directly select a folder with the storage location.

The first one is also mentioned in the [changelog](https://github.com/solid/node-solid-server/blob/release/v5.0.0/CHANGELOG.md)

**Comment by Leoudayan** [comment]
Ah great!. Many thanks for this. I have few questions regarding this. 

1. How does solid handle the session for each login? I have to login each time first and authorize the app each time to access my POD. If i update the ACL, can i skip the second part of authorizing the app?

2. Is it possible for you to prepare a file manager which lets reads the HTML file and lets us work like how it does with turtle?

Thanks for the changelog link.

**Comment by Otto-AA** [comment]
Regarding (2), it was a server side error which already has been fixed [with this PR](https://github.com/solid/node-solid-server/pull/1156). [Here](https://github.com/solid/node-solid-server/issues/1120) is the corresponding issue if you are interested. So if you use the code from the master branch to run the server, it should already work.

Regarding (1), the solid-auth-client stores a login token as far as I know. So for me, I only have to click on the "login" button in the file client and get logged in without entering my credentials another time. I don't think it is possible to write to the pod without being logged in (how would the server know, if it is really you? Because of the IP?). If you consider creating your own app with your own login system, I think you can store the login token, if that is what you want to do.

**Comment by Otto-AA** [comment]
I've added an `Accept: text/turtle` header for folder requests now. So if the server supports this behavior (<5.0.0 or 5.0.0 with the fix in the master branch) it should work now.

https://github.com/Otto-AA/solid-filemanager/commit/1d4343c713b5685a86cb01683ec9f334faf85872

**Comment by Leoudayan** [comment]
Hi,

Thanks a lot for this. I really appreciate your help. 

No, my code is not updated with the master branch. Its just the 5.0.0 release (npm install solid-server). I tried to follow the instructions to merge the master with the 5.0.0 release (https://github.com/solid/node-solid-server/blob/master/.travis.yml ) But getting error. Sorry for this small issues but i am new to web development and having troubles with basic things like this. Is it possible for you to suggest how to merge the master folder with 5.0.0 package?

**Comment by Otto-AA** [comment]
Sorry, I have no experience with setting up solid servers. Please ask there for further help on this. 

Are there any open questions regarding the solid-filemanager?

**Comment by Leoudayan** [comment]
Ah okie. I managed to install the master version using the following command

`npm install https://github.com/solid/node-solid-server`

Now i able to view the pod files through the directory. When i try to create a folder, it gives me an error that i dont have permission to do so. I am trying to your app domain in the POD .acl file to see whether the write feature work.  Thanks for your help :)

**Comment by Leoudayan** [comment]
Hi Otto,

When i tried to authorise your app through the .acl, it still gives me the same unauthorised error. I posted a post in the forum regarding this. It will be really great if you could have a look. 

https://forum.solidproject.org/t/acl-format-for-authorising-new-apps/1655

**Comment by Otto-AA** [comment]
You can look at [my response](https://forum.solidproject.org/t/acl-format-for-authorising-new-apps/1655/4?u=a_a) or the [README.md](https://github.com/Otto-AA/solid-filemanager/) for an easy way to authorize this app.
As of now, go to `your-solid-pod.com/profile/card#me`, click on "A" in the top and add "https://otto-aa.github.io" (without a slash at the end) with read/write access.

**Comment by Leoudayan** [comment]
Hi,

Thanks for this. I have added the access but still it didnt work. You can try by yourself. 
URL: https://testing.solid.open.ac.uk/
Username: Testing
Password: Solidapp@12345

I also checked the Acl file in the main folder but it didnt add any access to it. Please let me know if you find a way to make it work. Sorry for bothering you too much but you are the only expert in this area right now. :)

**Comment by Otto-AA** [comment]
I tested it and I was able to view the root and make a file in the private folder without any problem. Adding a file to the root directory doesn't work, i don't know if it should (or is restricted due to some reason).

Make sure that you have the newest version of the filemanager by making a complete reload (else it will keep the old version of the filemanager; this updating behavior will hopefully be changed in the future).

**Comment by Leoudayan** [comment]
Yes!! It worked. Thanks for it. :)

Is it possible to run this entire file system as a script rather than as a react app? Because, i am using a normal HTML file with java scripts to run my Plugin. I am not sure how to integrate the filemanager with the existing javascript. or its not possible to do this?

**Comment by Otto-AA** [comment]
What would be your use case? And what would be the difference to using an iframe or just opening it in a new tab?

**Comment by Leoudayan** [comment]
I try to store students learning records in the solid pod. Previously i used the solid file client prepared by jeff. It was quite easy to integrate and it was broken because of the new update. But i incorporated your suggestion in the file client and it worked! Thought i prefer your filemanager as it looks much better and have more options. The big i cant understand right now is that, how can i incorporate your app in my webpage in coding level. The scenerio is this. When students logs into our learning records page, they will first login with their solid pod. Now there will be a claim button in the webpage where the student can press and claim their learning records. Once pressed, it will open the solid file client (the one jeff prepared) and lets them to choose a folder to upload the learning records. Thats it. The files are stored in the POD. But when i wanted to integrate the filemanager, i was confused which code to copy as i never worked with react apps. This is the situation. If you could give some suggestions, that will be really great.

**Comment by Otto-AA** [comment]
If I understand you correctly you want an interface for the user to choose a storage location path? If yes, I am sorry but this file manager is built as a standalone app, so it would need refactoring to make it usable as a "function" which returns a path or uploads a file to a random location.

From where comes the data the students want to upload to their pod? Maybe you could let the user download it, and let them just open the file manager in a new tab and let them upload it there. Or is there a specific reason, they would need this to be in the same web page as your application? From your description I wouldn't know a reason, why it couldn't be splitted into download and upload on two different websites.

If you only mean the js-api for storing a file, most of it is in [this file](https://github.com/Otto-AA/solid-filemanager/blob/master/src/Api/Api.js) and the ones it imports in the top of the file. [Here](https://github.com/Otto-AA/solid-filemanager/blob/master/src/Actions/Actions.js) is the login function used. It should be rather easy to understand, but you could also use the solid-file-client for the same functionality which seems even more easy (and a fix for this issue is under consideration in the solid-file-client).

And integrating a react application to a normal webpage should be possible in general, but without integrating callbacks and parameters into solid-filemanager (which I don't plan to do in the near future) it seems rather pointless (it would behave nearly identical to an iframe). [Here](https://reactarmory.com/answers/how-to-integrate-react-into-existing-app) is more info on that if you are interested.

I hope this clarified some things. If you still have questions feel free to ask :)

**Comment by Leoudayan** [comment]
Hi Thanks a lot for your reply and sorry for the delayed reply. Just came back from a short vacation. 

Yes, you understood me correctly. From a student point of view, we try to provide as short steps as possible. If they download and put it into their POD, it will add more steps.

Many thanks for the links. I think even if it works like an iframe its fine (not sure whether all the functionalities of the app will be supported in the iframe version though). 

Your links and replies helped and clarified a lot. Thank you for spending your valuable time addressing my queries. Really appreciate it :)
